services:
  # PostgreSQL Database
  db:
    image: postgres:16
    container_name: tenantmgmt_db
    environment:
      POSTGRES_DB: tenantdb
      POSTGRES_USER: tenant
      POSTGRES_PASSWORD: tenant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenant -d tenantdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - tenant-network

  # Spring Boot Backend
  api:
    build: ./backend
    container_name: tenantmgmt_api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/tenantdb
      DB_USER: tenant
      DB_PASSWORD: tenant
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tenant-network

  # React Frontend
  frontend:
    build: ./frontend
    container_name: tenant-management-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - api
    networks:
      - tenant-network

volumes:
  pgdata:

networks:
  tenant-network:
    driver: bridge
