spring:
  application:
    name: tenant-management
  datasource:
    url: jdbc:h2:file:./data/dev-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/tenantdb}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:tenant}
    password: ${DB_PASSWORD:tenant}


